network/urls.py
from django.urls import path

from . import views

app_name = "network"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("post", views.post, name="post"),
    path("profile/<str:usernamestr>", views.profile, name="profile"),
    path("profile/<str:usernamestr>/<int:page>", views.profilePosts, name="profilePosts"),
    path("follow/<str:usernamestr>", views.follow, name="follow"),
    path("unfollow/<str:usernamestr>", views.unfollow, name="unfollow"),
    path("posts/<str:filter>/<int:page>", views.posts, name="posts"),
    path("like/<int:id>", views.like, name="like"),
    path("unlike/<int:id>", views.unlike, name="unlike"),
    path("editPost/<int:id>", views.editPost, name="editPost")
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    following = models.ManyToManyField('User', related_name="followers")
    liking = models.ManyToManyField('Post', related_name="likers")

    def follow(self, followed):
        self.following.add(followed)
        self.save()

    def unfollow(self, followed):
        self.following.remove(followed)
        self.save()

    def serialize(self):
        return {
            "username": self.username
        }

    def like(self, post):
        if self.username == post.user.username:
            raise Exception("Cannot like your own post")
        likes = self.liking.all()
        if post in likes:
            raise Exception("Cannot like a post twice")
        self.liking.add(post)
        self.save

    def unlike(self, post):
        likes = self.liking.all()
        if post not in likes:
            raise Exception("You must like a post before liking it")
        self.liking.remove(post)
        self.save

class Post(models.Model):
    message = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usrPosts", default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def post(self, message, user):
        self.message = message
        self.user = user
        self.save()

    def __str__(self):
        return self.message

    def serialize(self):
        return {
            "id": self.id,
            "message": self.message,
            "user": self.user.serialize(),
            "likes": self.likeCount(),
            "created_at": self.created_at.strftime("%b %-d %Y, %-I:%M %p")
        }

    def likeCount(self):
        return self.likers.all().count()

network/forms.py
from django.forms import ModelForm, HiddenInput
from .models import User, Post
from django.forms.widgets import Textarea

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['message']
        labels = {"message": "",}
        widgets = {
            'message': Textarea(attrs={ 'placeholder': 'Type your post here',
                                        'id': 'postMessageTextArea',
                                        'class': 'form-control',
                                        }),
        }

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.paginator import Paginator
import json

from .models import User, Post
from .forms import PostForm

itemsPerPage = 10

def index(request):
    # TODO: Pagination
    return render(request, "network/index.html", {
        "postForm": PostForm()
    });

def posts(request, filter, page):
    if request.method != "GET":
        raise Http404("Only GET requests allowed on this URL")
    if filter not in ["all", "following"]:
        raise Http404("Unrecognized filter")

    # filter: following
    if filter == "following":
        if not request.user.is_authenticated:
            raise Http404("Only logged in users allowed on this filter request")
        else:
            myUser = User.objects.get(username=request.user.username)
            usersFollowed = myUser.following.all()
            posts = Post.objects.filter(user__in=usersFollowed).order_by('-created_at')
            pages = Paginator(posts, itemsPerPage)
    # filter: all
    elif filter == "all":
        posts = Post.objects.all().order_by('-created_at')
        pages = Paginator(posts, itemsPerPage)

    # return filtered posts
    return JsonResponse([post.serialize() for post in pages.page(page)], safe=False)

def profilePosts(request, usernamestr, page):
    if request.method != "GET":
        raise Http404("Only GET requests allowed on this URL")

    try:
        u = User.objects.get(username=usernamestr)
        userPosts = u.usrPosts.all().order_by("-created_at")
        pages = Paginator(userPosts, itemsPerPage)
        # return filtered posts
        return JsonResponse([post.serialize() for post in pages.page(page)], safe=False)
    except Exception as e:
        raise Http404(f"Error while retrieving user data from {usernamestr}")

def profile(request, usernamestr):
    if request.method == "POST":
        raise Http404("Only GET requests allowed on this URL")

    following = False
    try:
        u = User.objects.get(username=usernamestr)
        followingCount = u.following.count()
        followersCount = u.followers.all().count()
        userPosts = u.usrPosts.all().order_by("-created_at")
        if request.user.is_authenticated:
            myUser = User.objects.get(username=request.user.username)
            following = (u in myUser.following.all())
    except Exception as e:
        raise Http404(f"Error while retrieving user data from {usernamestr}")

    return render(request, "network/profile.html", {
        "followingCount": followingCount,
        "followersCount": followersCount,
        "usernamestr": usernamestr,
        "following": following
    });

@login_required(login_url="network:login")
def follow(request, usernamestr):
    if request.method != "POST":
        raise Http404("Only POST requests allowed on this URL")
    if request.user.username == usernamestr:
        raise Http404("Recursive following not allowed")

    try:
        myUser = User.objects.get(username=request.user.username)
        u = User.objects.get(username=usernamestr)
        if u in myUser.following.all():
            raise Http404(f"Already following {usernamestr}")
        myUser.follow(u)
    except User.DoesNotExist:
        raise Http404(f"User {usernamestr} not found")
    return HttpResponse('OK')

@login_required(login_url="network:login")
def unfollow(request, usernamestr):
    if request.method != "POST":
        raise Http404("Only POST requests allowed on this URL")
    if request.user.username == usernamestr:
        raise Http404("Recursive following not allowed")

    try:
        myUser = User.objects.get(username=request.user.username)
        u = User.objects.get(username=usernamestr)
        if u not in myUser.following.all():
            raise Http404(f"You are not following {usernamestr}")
        myUser.unfollow(u)
    except User.DoesNotExist:
        raise Http404(f"User {usernamestr} not found")

    return HttpResponse('OK')

@login_required(login_url="network:login")
def like(request, id):
    if request.method not in ["GET","POST"]:
        raise Http404("Only POST requests allowed on this URL")
    if request.method == "POST":
        myUser = User.objects.get(username=request.user.username)
        post = Post.objects.get(pk=id)
        myUser.like(post)
        return HttpResponse('OK')
    if request.method == "GET":
        myUser = User.objects.get(username=request.user.username)
        post = Post.objects.get(pk=id)
        if post in myUser.liking.all():
            return JsonResponse({"message": "true"}, safe=False)
        else:
            return JsonResponse({"message": "false"}, safe=False)

@login_required(login_url="network:login")
def unlike(request, id):
    if request.method != "POST":
        raise Http404("Only POST requests allowed on this URL")

    myUser = User.objects.get(username=request.user.username)
    post = Post.objects.get(pk=id)
    myUser.unlike(post)
    return HttpResponse('OK')

@login_required(login_url="network:login")
def post(request):
    if request.method == "POST":
        f = PostForm(request.POST)
        if f.is_valid():
            newPost = f.save(commit=False)
            newPost.user = request.user
            newPost.save()
            f.save_m2m()
            return HttpResponseRedirect(reverse("network:index"))
        else:
            # TODO: Render error message
            return render(request, "network/index.html", {
                "postForm": PostForm()
            });
    else:
        raise Http404("Only POST request allowed on this URL")

@login_required(login_url="network:login")
def editPost(request, id):
    if request.method == "POST":
        post = Post.objects.get(pk=id)
        # Check if post edit request is from post owner
        if (post.user.username == request.user.username):
            data = json.loads(request.body)
            post.message = data.get("message")
            post.save()
            return JsonResponse(post.serialize(), status=201)
        else:
            return JsonResponse({"error": "Post edit not allowed"}, status=400)
    else:
        return JsonResponse({"error": "POST request required."}, status=400)

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    {% if user.is_authenticated %}
    <script>
    var csrftoken = '{{ csrf_token }}';
    var username = '{{ user.username }}';
    </script>
    <div class="btn-group btn-group-toggle" data-toggle="buttons" id="posts-selector">
      <label id="allPostsLabel" class="btn btn-outline-secondary active">
        <input type="radio" name="options" id="allPosts" autocomplete="off">All
      </label>
      <label id="followingPostsLabel" class="btn btn-outline-secondary">
        <input type="radio" name="options" id="followingPosts" autocomplete="off">Following
      </label>
    </div>
    {% endif %}

    <div id="posts-view">
      <h3>Latest Posts</h3>
    </div>
    <nav aria-label="Page navigation example" id="paginatorNav">
      <ul class="pagination justify-content-center">
        <li id="previuosListItemPag" class="page-item">
          <a id="previousLinkPag" class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        <li id="nextListItemPag" class="page-item">
          <a id="nextLinkPag" class="page-link" href="#">Next</a>
        </li>
      </ul>
    </nav>

    <div id="new-post-view">
      <h3>New Post</h3>
      {% if user.is_authenticated %}
      <div class="newpost_container">
        <form action="{% url 'network:post' %}" method="post" style="height:100%;width:100%">
          {% csrf_token %}
          <div class="form-group">
          {{ postForm.as_p }}
          </div>
          <input class="btn btn-primary" type="submit" value="Post">
        </form>
      </div>
      {% else %}
      Not signed in.
      {% endif %}
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'network/common.js' %}"></script>
    <script src="{% static 'network/network.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'network/styles.css' %}">
        {% block script %}
        {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>

            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item" id="userNavItem">
                        <a class="nav-link" href="/profile/{{ user.username }}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="/" id="posts-link">Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#" id="new-post-link">New Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>

        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
  <script>
  var csrftoken = '{{ csrf_token }}';
  var username = '{{ user.username }}';
  var profileusername = '{{ usernamestr }}'
  </script>
  <div class="container-fluid">
    <div id="profileHeaderContainer">
        <h3>{{ usernamestr }}'s profile</h3>
        {% if user.is_authenticated and request.user.username != usernamestr %}
        <button type="button" class="btn-sm btn-outline-primary rounded-pill" id="buttonFollow" data-following="{{ following }}" data-user="{{ usernamestr }}">Follow</button>
        {% endif %}
    </div>
    <p>Following <strong>{{ followingCount }}</strong> users and followed by <strong>{{ followersCount }}</strong> other users</p>
    <div class="container-fluid" id="user-posts-view">
      <h3>Latests Posts</h3>
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li id="previuosListItemPag" class="page-item">
          <a id="previousLinkPag" class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        <li id="nextListItemPag" class="page-item">
          <a id="nextLinkPag" class="page-link" href="#">Next</a>
        </li>
      </ul>
    </nav>
  </div>
{% endblock %}

{% block script %}
    <script src="{% static 'network/common.js' %}"></script>
    <script src="{% static 'network/profile.js' %}"></script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}